### ISSUE TITLE
Assembly polarity in accordance IPC-7351C

### ISSUE THREAD

**Issue by eldarkg** [KiCad/Crystals.pretty#23] opened 2017-06-06 17:10 UTC
Should be
![Polarity](https://user-images.githubusercontent.com/5782069/26841971-e47e2758-4af3-11e7-901c-5605e84be23e.png)

**Comment by poeschlr** [comment] 2017-06-06 18:27
Duplicate of https://github.com/KiCad/Oscillators.pretty/issues/6

**Comment by eldarkg** [comment] 2017-06-07 18:12
@poeschlr
Affected footprints:
Crystal_SMD_*
Resonator_SMD_*

**Comment by eldarkg** [comment] 2017-06-07 18:15
@poeschlr, It is not duplicate. We use separated issues for each repository. You should open my bug

**Comment by poeschlr** [comment] 2017-06-07 23:22
I thought this was a general statement about the library convention. (Discussions about the library convention should be in one issue only. Otherwise inconsistencies might occur.)

I will reopen this issue but you need to give more details on how the footprints violate the standard.
(Make a screenshot and show what's wrong. This is what you should have done in the first place. Simply posting a picture of a standard that is already covered by our library convention is not really helpful.)

Also this is a community driven effort for creating a library. If you find a problem: Fork the repo, fix the footprint and create a pull request. (There is nobody who will go around and fix stuff. We librarians try to get all libs up to the defined standard but we don't have unlimited time. Most of our time is spent on checking new contributions.)
This issue can serve as a place to discus how to fix the specific problems of this library.
**But again: i would like to fokus the discussion about the library standard in one issue. This is why i originally closed this thread and marked it as a duplicate of KiCad/Oscillators.pretty#6**

**Comment by eldarkg** [comment] 2017-06-08 16:19
@poeschlr I know about small manpower. Maybe I'm wrong but I thought that it is resolve by a generator script (no manual fixing).
Examples:
![1](https://user-images.githubusercontent.com/5782069/26939152-184b874c-4c7f-11e7-9eb9-92939f2caf3d.png)
![2](https://user-images.githubusercontent.com/5782069/26939151-184b4c50-4c7f-11e7-8d86-2427d92b487e.png)
Should be like this:
![fab_layer](https://user-images.githubusercontent.com/5782069/26939218-57b75cda-4c7f-11e7-8160-96cedec3e306.png)

**Comment by poeschlr** [comment] 2017-06-08 18:16
It seems at least some of the crystals might be script generated (so it should be possible to fix them via the script.)
https://github.com/pointhi/kicad-footprint-generator/tree/master/scripts

**Comment by jkriege2** [comment] 2017-06-08 20:19
Nearly all of them are script-generated ... 
https://github.com/pointhi/kicad-footprint-generator/blob/master/scripts/Crystals_Resonators_SMD/make_crystal_smd.py
https://github.com/pointhi/kicad-footprint-generator/blob/master/scripts/Crystals_Resonators_THT/make_crystal.py

Best,
JAN

**Comment by evanshultz** [comment] 2017-07-18 20:43
@jkriege2 @poeschlr I'm not that familiar with the scripts. Are either of you able to review this and make any necessary changes?

**Comment by SchrodingersGat** [comment] 2017-11-21 11:41
@eldarkg  I'm closing this issue as this repo is now marked as legacy. Please readdress this issue to https://github.com/kicad/kicad-footprints

**Closed as completed by SchrodingersGat** 2017-11-21 11:41 UTC
